### PR TITLE
patch enable RCall can used in embedded julia 

### PR DESCRIPTION
**Pull request by armgong**
https://github.com/armgong/rcall (r package prototype) is R package embedded julia into R through RCall.jl

### CODE REVIEW

**Comment by simonbyrne** [comment]
Rather than create a global variable in Main, it might be better to try to check directly if R is running. There doesn't seem to be an API to querythis, but based on this discussion:
https://stat.ethz.ch/pipermail/r-devel/2015-May/071069.html
you could try
```julia
R_inited = unsafe_load(cglobal((:R_NilValue,libR),Ptr{Void})) != C_NULL
```

**Comment by armgong** [comment]
thanks,  i will try this tomorrow, and resummit patch.

**Comment by armgong** [comment]
btw, after this pull request , rjulia can call RCall.jl no need modify,so I delete https://github.com/armgong/rcall

**Comment by simonbyrne** [comment]
Nice! I'm super excited about having a 2-way interface.

**Pull request merged**
