### PR TITLE
dirty fix for string array containing NAs

### PR DESCRIPTION
**Pull request by randy3k**
As `rcopy("NA")` returns a string `"NA"`, this dirty fix will work for most cases. But it doesn't differentiate between the real `NA` and the string `"NA"`.

Related to #32

### CODE REVIEW

**Comment by dmbates** [comment]
I'm not sure I understand the rationale.  `R_NaString` is a `CharSxp` with contents "NA".  The reason I would want to use `bytestring(R_NaString)` instead of comparison to `"NA"` is in case that string ever changed.

Am I missing what the purpose of the pull request is?  In other words, am I doing the comparison wrong or just inefficiently?

**Comment by randy3k** [comment]
There is no method of `bytestring` on `CharSxp`. If I understand your rationale, you wanted to compare it with `rcopy(R_NaString)`, which is `"NA"`.

**Comment by dmbates** [comment]
I would prefer the comparison to be against `rcopy(R_NaString)' then.

**Comment by randy3k** [comment]
alright, I will make the change +1

**Pull request merged**
