### PR TITLE
setHook for eventloop

### PR DESCRIPTION
**Pull request by randy3k**
It is an attempt to handle #49. In here, "plot.new" and "grid.newpage" hooks are being used to trigger the loop.

### CODE REVIEW

**Comment by randy3k** [comment]
@simonbyrne any comments about the hooks?

**Comment by simonbyrne** [comment]
Sorry I haven't had a chance to look at this yet: I'll try to get a look at it in the next few days.

**Comment by simonbyrne** [comment]
This was roughly what I had in mind. 
* Wouldn't you want to make the call to `rgui_start` silent, as the hook can be invoked multiple times?
* Does `plot.new` not get called before `grid.newpage`?

**Comment by randy3k** [comment]
The hook is called everytime a plot is made, and there are two major plotting devices, `graphics` and `grid`. `plot.new` is needed for R base, for example, `plot` and `hist`. And `grid.newpage` is needed for example, `ggplot2` which uses `grid`.

**Comment by randy3k** [comment]
@simonbyrne Somehow Appveyor CI is stuck, could you restart it?

**Comment by randy3k** [comment]
Look like Appveyor fails due to Dataframes.jl. I guess it is ready to merge.

**Pull request merged**
