### PR TITLE
run R_ProcessEvents on Windows

### LINKED ISSUE #104: ccall could not find R_checkActivity
I get the following error on Windows with the master version of RCall:

````
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.5 (2016-03-18 00:58 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> using RCall

julia> x = randn(100);

julia> using DataFrames

julia> df = DataFrame(x=x, y=[x[1:50];2x[51:100]] + 0.1randn(100), tp=[zeros(Int,50), ones(Int, 50)]);
WARNING: [a,b] concatenation is deprecated; use [a;b] instead
 in depwarn at deprecated.jl:73
 in oldstyle_vcat_warning at abstractarray.jl:29
 in vect at abstractarray.jl:32
while loading no file, in expression starting on line 0

julia> @rput df;

julia> @rlibrary ggplot2
WARNING: RCall.jl Need help? Try the ggplot2 mailing list:
http://groups.google.com/group/ggplot2.

julia> reval(rparse("qplot(x, y, data = df, color = factor(tp))"))
RCall.RObject{RCall.VecSxp}

ERROR (unhandled task failure): ccall: could not find function R_checkActivity in library C:\Program Files\R\R-3.2.5\bin\x64\R
 in process_events at C:\Users\anthoff\.julia\v0.4\RCall\src\eventloop.jl:7

julia>
````

### PR DESCRIPTION
**Pull request by randy3k**
it should fix #104

### CODE REVIEW

**Comment by davidanthoff** [comment]
Yes, that fixes things on my end! Thanks!

**Comment by randy3k** [comment]
I am a bit surprised that no one else has reported this issue until now...perhaps only a handful of people are using RCall on Windows.

**Comment by davidanthoff** [comment]
Well, to be honest, I'd be surprised if there are more than a few users overall, the lack of a "how to use this package" like documentation makes it almost impossible to get started with the package...

**Comment by randy3k** [comment]
The failure is not relevant to the PR.

**Comment by davidanthoff** [comment]
@randy3k or @simonbyrne could you tag a new release that incorporates this fix? Thanks!

**Comment by randy3k** [comment]
I think it makes sense to release a patch for this. But I would like to wait and see @simonbyrne has anything to add to the next release.

**Comment by simonbyrne** [comment]
Not soon, go ahead and tag it.

**Comment by randy3k** [comment]
@davidanthoff 
Will release it when #107 is confirmed to be fixed.

**Pull request merged**
